from django.conf.urls.defaults import patterns, include, url


urlpatterns = patterns('',
    url(r'^$', 'stacktach.views.welcome', name='welcome'),

    url(r'stacky/deployments/$', 'stacktach.stacky_server.do_deployments'),
    url(r'stacky/events/$', 'stacktach.stacky_server.do_events'),
    url(r'stacky/hosts/$', 'stacktach.stacky_server.do_hosts'),
    url(r'stacky/uuid/$', 'stacktach.stacky_server.do_uuid'),
    url(r'stacky/timings/$', 'stacktach.stacky_server.do_timings'),
    url(r'stacky/timings/uuid$', 'stacktach.stacky_server.do_timings_uuid'),
    url(r'stacky/summary/$', 'stacktach.stacky_server.do_summary'),
    url(r'stacky/request/$', 'stacktach.stacky_server.do_request'),
    url(r'stacky/show/(?P<event_id>\d+)/$',
                                        'stacktach.stacky_server.do_show'),
    url(r'stacky/watch/(?P<deployment_id>\d+)/$',
                                        'stacktach.stacky_server.do_watch'),
    url(r'stacky/kpi/$', 'stacktach.stacky_server.do_kpi'),
    url(r'stacky/kpi/(?P<tenant_id>\d+)/$', 'stacktach.stacky_server.do_kpi'),
    url(r'stacky/usage/launches/$',
        'stacktach.stacky_server.do_list_usage_launches'),
    url(r'stacky/usage/deletes/$',
        'stacktach.stacky_server.do_list_usage_deletes'),
    url(r'stacky/usage/exists/$',
        'stacktach.stacky_server.do_list_usage_exists'),

    url(r'db/usage/launches/$',
        'stacktach.dbapi.list_usage_launches'),
    url(r'db/usage/launches/(?P<launch_id>\d+)/$',
        'stacktach.dbapi.get_usage_launch'),
    url(r'db/usage/deletes/$',
        'stacktach.dbapi.list_usage_deletes'),
    url(r'db/usage/deletes/(?P<delete_id>\d+)/$',
        'stacktach.dbapi.get_usage_delete'),
    url(r'db/usage/exists/$', 'stacktach.dbapi.list_usage_exists'),
    url(r'db/usage/exists/(?P<exist_id>\d+)/$',
        'stacktach.dbapi.get_usage_exist'),

    url(r'^(?P<deployment_id>\d+)/$', 'stacktach.views.home', name='home'),
    url(r'^(?P<deployment_id>\d+)/details/(?P<column>\w+)/(?P<row_id>\d+)/$',
        'stacktach.views.details', name='details'),
    url(r'^(?P<deployment_id>\d+)/search/$',
        'stacktach.views.search', name='search'),
    url(r'^(?P<deployment_id>\d+)/expand/(?P<row_id>\d+)/$',
        'stacktach.views.expand', name='expand'),
    url(r'^(?P<deployment_id>\d+)/latest_raw/$',
        'stacktach.views.latest_raw', name='latest_raw'),
    url(r'^(?P<deployment_id>\d+)/instance_status/$',
        'stacktach.views.instance_status', name='instance_status'),
)
