export STACKTACH_DB_NAME="stacktach"
export STACKTACH_DB_HOST=""
export STACKTACH_DB_USERNAME="root"
export STACKTACH_DB_PASSWORD="password"
export STACKTACH_DB_PORT="3306"
export STACKTACH_INSTALL_DIR="/srv/www/stacktach/"
export STACKTACH_DEPLOYMENTS_FILE="/srv/www/stacktach/stacktach_worker_config.json"
export STACKTACH_VERIFIER_CONFIG="/srv/www/stacktach/stacktach_verifier_config.json"

export DJANGO_SETTINGS_MODULE="settings"
