import os
STACKTACH_DB_ENGINE = 'django.db.backends.mysql'
STACKTACH_DB_NAME = 'stacktach'
STACKTACH_DB_HOST = 'localhost'
STACKTACH_DB_USERNAME = 'stacktach'
STACKTACH_DB_PASSWORD = ''
STACKTACH_DB_PORT = '3306'
STACKTACH_INSTALL_DIR = os.environ.get('STACKTACH_INSTALL_DIR', '')
STACKTACH_DEPLOYMENTS_FILE = os.environ.get('STACKTACH_DEPLOYMENTS_FILE', '')
